name: coventry_phoenix_fc
description: A Flutter project for Coventry Phoenix, Football Club.

publish_to: 'none'

version: 1.0.9+9

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.2.3
  flutter_bloc: ^7.0.0   # Adjust if you find that a higher version is needed
  flutter_lints: ^4.0.0
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  cloud_functions: ^5.0.3
  firebase_messaging: ^15.0.3
  firebase_auth: ^5.1.2
  firebase_crashlytics: ^4.0.3
  firebase_analytics: ^11.2.0
  firebase_storage: ^12.1.1
  provider: ^6.1.2
  http: ^1.2.2
  syncfusion_flutter_core: ^26.1.42
  syncfusion_flutter_datagrid: ^26.1.42
  syncfusion_localizations: ^26.1.42
  syncfusion_flutter_charts: ^26.1.42
  syncfusion_flutter_gauges: ^26.1.42
  google_nav_bar: ^5.0.6
  flutter_staggered_grid_view: ^0.7.0
  transparent_image: ^2.0.1
  cached_network_image: ^3.3.1
  line_icons: ^2.0.3
  avatar_glow: ^3.0.1
  pie_chart: ^5.3.2
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  toast: ^0.3.0
  font_awesome_flutter: ^10.7.0
  flutter_inset_box_shadow: ^1.0.8
  blurrycontainer: ^2.1.0
  flutter_neumorphic: ^3.2.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  flutter_swiper_null_safety: ^1.0.2
  clay_containers: ^0.3.4
  confetti: ^0.7.0
  parallax_rain: ^1.1.1
  flutter_local_notifications: ^17.2.1+2
  adaptive_theme: ^3.6.0
  flutter_riverpod: ^2.5.1
  path_provider: ^2.1.3
  flutter_inappwebview: ^6.0.0
  collection: ^1.18.0
  rxdart: ^0.27.7
  onesignal_flutter: ^5.2.2
  photo_view: ^0.15.0
  giffy_dialog: ^2.1.0
  esys_flutter_share_plus: ^2.2.0
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.6
  youtube_player_flutter: ^9.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0   # Update to match flutter_localizations
  image: ^4.2.0
  image_gallery_saver: ^2.0.3
  flutter_colorpicker: ^1.1.0
  flutter_text_drawable: ^1.0.0
  image_picker: ^1.1.2
  simple_icons: ^10.1.3
  youtube: ^2.0.0
  flutter_spinner_time_picker: ^0.2.1
  launch_review: ^3.0.1
  telephony: ^0.2.0
  otp_text_field: ^1.1.3
  sms_autofill: ^2.4.0
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  fl_chart: ^0.68.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/cpfc_logo_android_ios.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/json/
    - assets/
  uses-material-design: true
